
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package fes.aragon.compilador;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int llaveC = 14;
  public static final int mayorA = 5;
  public static final int id = 15;
  public static final int llaveA = 13;
  public static final int mayorIgual = 7;
  public static final int parC = 12;
  public static final int parA = 11;
  public static final int igualA = 8;
  public static final int num = 16;
  public static final int semi = 9;
  public static final int EOF = 0;
  public static final int IF = 2;
  public static final int menorA = 4;
  public static final int ELSE = 3;
  public static final int menorIgual = 6;
  public static final int asig = 10;
  public static final int error = 1;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE",
  "menorA",
  "mayorA",
  "menorIgual",
  "mayorIgual",
  "igualA",
  "semi",
  "asig",
  "parA",
  "parC",
  "llaveA",
  "llaveC",
  "id",
  "num"
  };
}

